languageCode = "en-us"
title = "A11y Ref"
baseURL = "https://kerseyi.github.io/cupper-2/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "A repository of accessible component code patterns, references, and educational materials."
  codePenUser = "iankonlineada"
