name = "Cupper"
description = "A repository of accessible component code patterns, references, and educational materials."
homepage = "https://www.iankersey.com"
tags = ["inclusive design", "accessibility"]
min_version = 0.1

SectionPagesMenu = "main"

[author]
  name = "Ian Kersey"
  homepage = "https://www.iankersey.com"

[taxonomies]
  tag = "tags"
  wcag = "wcag"
  principle = "principles"
